# Generated by Django 5.0.4 on 2024-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('caption', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.BooleanField(default=True)),
                ('navs', models.BooleanField(default=True)),
                ('pags', models.BooleanField(default=True)),
                ('auto', models.BooleanField(default=True)),
                ('delay', models.IntegerField(default=5)),
                ('stopMouseHover', models.BooleanField(default=True)),
            ],
        ),
    ]
